services:
  api:
    build: .
    container_name: reserva_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://reserva_user:reserva_pass@postgres:5432/reserva_db
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: reserva_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: reserva_user
      POSTGRES_PASSWORD: reserva_pass
      POSTGRES_DB: reserva_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

